version: 2.1
orbs:
  node: circleci/node@12.13.0
  heroku: circleci/heroku@1.0.0
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout

      - restore_cache:
        keys:
          - node-v1-{{ checksum "package.json" }}
          - node-v1-      
 
      - run: yarn install
      
      - save_cache:
        key: node-v1-{{ checksum "package.json" }}
        paths:
          - node_modules

          
      - run: yarn build
 deploy:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: heroku deploy
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
          - build
          filters:
            branches:
              only: master
