version: 2.1

orbs:
  heroku: circleci/heroku@1.0.1

workflows:
  heroku_deploy:
    jobs:
      - deploy-prod
jobs:
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - run:
          name: Setup Heroku
          command: bash .circleci/setup-heroku.sh
      - heroku/deploy-via-git:
          only-branch: master
  deploy-prod:  
      machine:
          image: circleci/classic:edge
      steps:
          - checkout
          - run:
              name: heroku maintenance on
              command: heroku maintenance:on --app ${HEROKU_APP_NAME}
          - run:
              name: heroku deploy
              command: |
                  git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
          - run:
              name: heroku maintenance off
              command: heroku maintenance:off --app ${HEROKU_APP_NAME}
  build:
    docker:
      - image: circleci/node:12.13-stretch-browsers
    working_directory: ~/app-drawn
    steps:
      - checkout
      
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn build
        
